[project]
name = "translator-service"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "python-json-logger>=3.3.0",
    "uvicorn>=0.35.0",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
