name: Language-Translater CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.0"

      - name: Lock file check
        run: uv lock --check

      - name: Install backend dependencies
        run: uv sync --frozen

      - name: Lint check
        run: uv run ruff check --output-format=github ./

      - name: Format check
        run: uv run ruff format --diff ./

      - name: Type check
        run: MYPY_PATH./,translater_service uv run mypy ./